### ISSUE TITLE
Feature request: including multiple public keys

### ISSUE THREAD

**Issue by Prodeguerriero** [coreprocess/linux-unattended-installation#29]
Hi there,

I know it's probably a bit out of scope, but would you consider the option of accepting at least two ssh public keys?

Thanks

**Comment by coreprocess** [comment]
@Prodeguerriero Feel free to open a PR for that :-). You could change the parameter so that it accepts a comma separated list of key files.

**Comment by Prodeguerriero** [comment]
> @Prodeguerriero Feel free to open a PR for that :-). You could change the parameter so that it accepts a comma separated list of key files.

Sure, I will give it a go, or at least I'll try.

**Comment by Prodeguerriero** [comment]
@coreprocess I ended up opting for the lazy solution. I used `cat` to create a single file with the keys I needed, than fed it to the script. 😅

**Comment by coreprocess** [comment]
@Prodeguerriero lazy is the right choice in this case, I guess :-)
